// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLg193AwryQYE9czVLr8lJhJT8_mELgnE',
    appId: '1:802814727533:android:4f01dbd4dbe4d01e6d3664',
    messagingSenderId: '802814727533',
    projectId: 'walkwise-v2',
    storageBucket: 'walkwise-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsjUodS4q_C3geYOMIeFnlJ1ZMUcM4zZo',
    appId: '1:802814727533:ios:e7230d0e03c585486d3664',
    messagingSenderId: '802814727533',
    projectId: 'walkwise-v2',
    storageBucket: 'walkwise-v2.firebasestorage.app',
    iosBundleId: 'dev.dizzpy.walkwise',
  );
}
